Lesson1
MaksimLakatkouOld/jet pull request #1
Opened 2021-10-05 06:27 UTC by MaksimKuzur

Lesson1 task done

2021-10-05 07:22 UTC, igr-ik commented on sources/views/data.js
> +									scrollX: false,
Соблюдай единообразие в форматировании, где-то у тебя есть пробел после двоеточия, где-то нет.

2021-10-05 07:22 UTC, igr-ik commented on sources/views/data.js
> +										"on_click_delete": function(e, id) {
Здесь можно и так написать, будет работать
on_click_delete(e, id) { ... }

2021-10-05 07:22 UTC, igr-ik commented on sources/views/start.js
> +export default class DataView extends JetView{
Такое имя "DataView" у одного класса уже есть.

2021-10-05 10:57 UTC, HelgaListopad requested changes
Для всех виджетов, кроме multiview cells

2021-10-05 10:57 UTC, HelgaListopad commented on sources/views/data.js
> +					cells: [
Лучше всего будет использовать для `cells` два JetView - одно для таблицы с формой Countries, второе для Statuses.
https://webix.gitbook.io/webix-jet/part-iii-practical-tasks/nesting-jet-views-into-webix-widgets#1-multiview-control

Учти, пожалуйста, что `parse`/`bind` нужно будет вызывать в том классе, где расположены виджеты

2021-10-05 10:57 UTC, HelgaListopad commented on sources/views/start.js
> +				{ view:"list", id: "listContacts", template:"#id#. #Name#, #Email#, status #Status#, country #Country#" },
`id` => `localId`

2021-10-05 10:57 UTC, HelgaListopad commented on sources/views/data.js
> +													$$("formForStatuses").save()
`this.getFormView().save()`

2021-10-05 10:57 UTC, HelgaListopad commented on sources/views/data.js
> +					cells: [
Кроме того, в этих структурах и других модулях старайся **не использовать** глобальные ID (например, для таблиц, форм и листов).
`localId` внутри класса предпочтительнее и безопаснее.

Где глобальные айдишки допустимы (и можно оставить)
- IDs of multiview cells (см. документацию по ссылке выше)
- top app menu (уже сделано в sources/views/top.js)

2021-10-07 08:12 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +									scrollX: false,
исправил

2021-10-07 08:12 UTC, MaksimKuzur commented on sources/views/data.js
> +										"on_click_delete": function(e, id) {
исправил

2021-10-07 08:12 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +export default class DataView extends JetView{
исправил

2021-10-07 08:12 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +					cells: [
исправил

2021-10-07 08:12 UTC, MaksimKuzur commented on sources/views/start.js
> +				{ view:"list", id: "listContacts", template:"#id#. #Name#, #Email#, status #Status#, country #Country#" },
исправил

2021-10-07 08:12 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +													$$("formForStatuses").save()
исправил

2021-10-07 09:45 UTC, igr-ik approved these changes

2021-10-07 09:45 UTC, igr-ik commented on sources/views/data.js
> +						{ $subview: DataCountriesView, id: "tabCountries" },
Почему $subview? Лучше переделай в cols или rows. $subview тут не подходит.

2021-10-07 09:45 UTC, igr-ik commented on sources/views/dataCountriesView.js
> +		this.$$("tableCountries").parse(countries);
Получения вьюшек вынеси в отдельный метод, потом уже используй его где угодно, например:
$getTableCountries() {
return this.$$("tableCountries");
}

либо:
get $tableCountries() {
return this.$$("tableCountries");
}

Символом $ обозначаются методы из которых возвращаются вебиксовые вьюшки

2021-10-07 09:45 UTC, igr-ik commented on sources/views/settings.js
> +export default {
Сделай классом

2021-10-07 10:47 UTC, HelgaListopad commented on sources/views/data.js
> +						{ $subview: DataCountriesView, id: "tabCountries" },
Подходит по документации и возможностям джета (приводила [пример](https://webix.gitbook.io/webix-jet/part-iii-practical-tasks/nesting-jet-views-into-webix-widgets#1-multiview-control) в ревью) - я предлагаю оставить именно этот вариант

2021-10-07 10:59 UTC, HelgaListopad approved these changes

2021-10-07 12:33 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +						{ $subview: DataCountriesView, id: "tabCountries" },
принято

2021-10-07 12:33 UTC, MaksimLakatkouOld commented on sources/views/dataCountriesView.js
> +		this.$$("tableCountries").parse(countries);
исправил

2021-10-07 12:33 UTC, MaksimKuzur commented on sources/views/settings.js
> +export default {
исправил

2021-10-07 13:03 UTC, merged