Lesson2 completed
MaksimLakatkouOld/jet pull request #2
Opened 2021-10-09 16:08 UTC by MaksimLakatkouOld

2021-10-11 08:15 UTC, igr-ik commented on sources/locales/en.js
> +};
В русской локализации побольше перевода. Приведи русскую и английскую локализации к единому виду. Нужно чтобы количество и название полей совпадало, но значения полей разных переводов.

2021-10-11 08:15 UTC, igr-ik commented on sources/locales/ru.js
> +	"Settings" :  "Настройки",
Дубликат, на пятой строчке уже есть "Settings"

2021-10-11 08:15 UTC, igr-ik commented on sources/views/formForListContacts.js
> +					placeholder: "Type here.."
"Type here.." тоже нужно в локализацию добавить

2021-10-11 08:15 UTC, igr-ik commented on sources/views/dataCountriesView.js
>  	init() {
Разделяй методы класса между собой одной пустой строкой. Исправь это во всех классах.

2021-10-11 08:15 UTC, igr-ik commented on sources/views/formForListContacts.js
> +								const listContactItemValues = this.getRoot().getValues();
this.getRoot().getValues()
Создай метод в классе, например: $getForm(), и через него обращайся к компоненту.

2021-10-11 08:15 UTC, igr-ik commented on sources/views/formForListContacts.js
> +		this.$$("formForListContacts").setValues(listContactItem);
Где-то через this.getRoot() к форме обращаешься, где-то через this.$$("formForListContacts")

Придерживайся единого стиля! Вынеси получения компонента в отдельный метод, и через него работай с формой с любого места.

2021-10-11 08:15 UTC, igr-ik commented on sources/views/settings.js
> +		const value = this.getRoot().queryView({ view:"segmented" }).getValue();
Добавь в view: "segmented" localId и через него обращайся к компоненту

2021-10-11 08:15 UTC, igr-ik commented on sources/views/start.js
> +							template: "#id#. #Name#, #Email#, status #Status#, country #Country# <span class='on_click_delete webix_icon wxi-close'></span>",
По нормальному, текст в этом template, тоже нужно было бы локализовать.

2021-10-11 08:15 UTC, igr-ik commented on sources/views/start.js
> +										contactsCollection.add({id: idNewListContactItem, Name: "New name", Email: "New Email", Status: "New status", Country: "New country", });
Опять объект в одну строку...

2021-10-11 08:15 UTC, igr-ik commented on sources/views/start.js
> +			var selectedListContactItem = this.$getListContacts().getSelectedId();
var ?

2021-10-11 08:15 UTC, igr-ik commented on sources/views/start.js
> +			this.$getListContacts().select(this.getParam("id"));
Если используешь 2 или более вызова одного и того же метода, то вынеси результат его выполнения в переменную потом используй ее
const contactId = this.getParam("id");

2021-10-11 09:10 UTC, MaksimLakatkouOld commented on sources/locales/en.js
> +};
Исправил

2021-10-11 09:10 UTC, MaksimLakatkouOld commented on sources/locales/ru.js
> +	"Settings" :  "Настройки",
Исправил

2021-10-11 09:10 UTC, MaksimLakatkouOld commented on sources/views/formForListContacts.js
> +					placeholder: "Type here.."
Исправил

2021-10-11 09:10 UTC, MaksimKuzur commented on sources/views/dataCountriesView.js
>  	init() {
Исправил

2021-10-11 09:10 UTC, MaksimKuzur commented on sources/views/formForListContacts.js
> +								const listContactItemValues = this.getRoot().getValues();
Исправил

2021-10-11 09:10 UTC, MaksimLakatkouOld commented on sources/views/formForListContacts.js
> +		this.$$("formForListContacts").setValues(listContactItem);
Исправил

2021-10-11 09:10 UTC, MaksimKuzur commented on sources/views/settings.js
> +		const value = this.getRoot().queryView({ view:"segmented" }).getValue();
Исправил

2021-10-11 09:10 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +							template: "#id#. #Name#, #Email#, status #Status#, country #Country# <span class='on_click_delete webix_icon wxi-close'></span>",
Исправил

2021-10-11 09:10 UTC, MaksimKuzur commented on sources/views/start.js
> +										contactsCollection.add({id: idNewListContactItem, Name: "New name", Email: "New Email", Status: "New status", Country: "New country", });
Исправил

2021-10-11 09:10 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +			var selectedListContactItem = this.$getListContacts().getSelectedId();
Исправил

2021-10-11 09:10 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +			this.$getListContacts().select(this.getParam("id"));
Исправил

2021-10-11 11:05 UTC, igr-ik commented on sources/views/start.js
> +							template: "#id#. #Name#, #Email#, " + _("status") + " #Status#, " + _("country") + " #Country# <span class='on_click_delete webix_icon wxi-close'></span>",
Чтобы не конкатенировать строку через плюсы, используй строку шаблонизатор `...`
`#id#. #Name#, #Email#, ${_("status")} #Status#, ${_("country")} #Country# <span class='on_click_delete webix_icon wxi-close'></span>`

2021-10-11 11:05 UTC, igr-ik commented on sources/views/settings.js
> +	$getSegmentedLocaleValue() {
Не совсем то что я имел ввиду. Это хорошо что ты создал метод для более удобного получения значения вью "segmented", но сам вью ты как потом получать будешь? Тебе нужно было сразу создать метод для получения вью, а потом во втором методе его использовать.

$getSegmentedView() {
return this.$$("segmentedLocale");
}

getSegmentedViewValue() {
return this.$getSegmentedView().getValue();
}

Знаком $ в начале метода, обозначаются методы которые возвращают вебик вью. Это нужно для быстрого понимания. для чего этот метод. В других методах которые не возвращают вебик вью, не нужно ставить $

2021-10-11 13:05 UTC, HelgaListopad requested changes

2021-10-11 13:05 UTC, HelgaListopad commented on sources/views/start.js
> +									contactsCollection.remove(id);
Если удаляется запись, на которой стоял селект, нужно
- очистить форму
- сбросить параметр в URL (это делается через show)

2021-10-11 13:05 UTC, HelgaListopad commented on sources/views/start.js
> +		this.$getListContacts().select(1);
Не очень хорошо писать именно такую последовательность действий.
onAfterSelect, который передаёт параметр в  URL, задаётся позже, поэтому этот выбранный айтем не попадает в URL
Кроме того, ниже ты пишешь
```js
const contactId = this.getParam("id");
if (contactId)
	this.$getListContacts().select(contactId);
```
Это сделано верно, но в дополнение к этому ты мог бы здесь же предусмотреть селект первого контакта, если в URL нет параметра ( и не по id == 1, а по `getFirstId()` )

2021-10-11 16:14 UTC, MaksimKuzur commented on sources/views/start.js
> +							template: "#id#. #Name#, #Email#, " + _("status") + " #Status#, " + _("country") + " #Country# <span class='on_click_delete webix_icon wxi-close'></span>",
Исправил

2021-10-11 16:14 UTC, MaksimLakatkouOld commented on sources/views/settings.js
> +	$getSegmentedLocaleValue() {
Исправил

2021-10-11 16:14 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +									contactsCollection.remove(id);
Исправил

2021-10-11 16:14 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +		this.$getListContacts().select(1);
Исправил

2021-10-11 16:19 UTC, HelgaListopad approved these changes

2021-10-12 07:22 UTC, igr-ik approved these changes

2021-10-12 11:54 UTC, merged